### ISSUE TITLE
Test library on the robot using a Yarp module

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/superquadric-lib#13]
Efficiency and effectiveness of the library is going to be tested on the iCub robot.

**Comment by giuliavezzani** [comment]
Once this implementation will be completed, also add description of how to use the library in real-time demo (multiple visualization and hand selection).

**Comment by giuliavezzani** [comment]
First tests on the iCub done :tada: The computation and visualization were fine, no movements have been tested yet.
In order to properly test multi-superquadric method:
- table height need to be recalibrated;
- point clouds need to be better (tests on R1?)

**Comment by xEnVrE** [comment]
> point clouds need to be better (tests on R1?)

Can I also suggest to test it using iCub's `SFM` with the option `--use_sgbm`? It uses opencv `cv::StereoSGBM` that produces more sparse point clouds, when texture is missing,  but preserves more the shape of the object as compared to `libELAS`.

**Comment by giuliavezzani** [comment]
You'e totally right, I forgot about it.

**Comment by giuliavezzani** [comment]
I tested with `sgbm` option. The situation is slightly better, even if I'd like to test it also with R1 sensors. Thanks anyway @xEnVrE :smile:
