### ISSUE TITLE
Make sure to properly redefined allocator of classes that contains fixed-size vectorizable Eigen object to respect alignement

### ISSUE THREAD

**Issue by traversaro** [robotology/superquadric-lib#17]
See https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html . In most cases, the fix is just to add the `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` macro in the public section of the affected  classes. 

[`SuperqGrasp::GraspPoses`](https://github.com/robotology/superquadric-lib/blob/d3e084527cdb704f2beecb63f50fcb167d7ed8f1/src/SuperquadricLib/SuperquadricGrasp/include/graspPoses.h#L31) is an example of affected class.

**Comment by giuliavezzani** [comment]
Sorry @traversaro, I haven't sees this issue! I'll fix it asap, thanks for spotting!

**Comment by giuliavezzani** [comment]
Fixed in [088da29](https://github.com/robotology/superquadric-lib/commit/088da29144fea54764bf5d2c588cc53c08e61b2e).
