### ISSUE TITLE
Problems in using Ipopt

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/superquadric-lib#2]
In the current implementation of the library, the user is required to do in his code:

```
#define HAVE_CSTDDEF
#include <IpTNLP.hpp>
#undef HAVE_CSTDDEF
```

**Comment by traversaro** [comment]
That is unfortunately a problem of iPOPT at the debian packaging level, see https://github.com/ghorn/debian-coinor-ipopt/issues/2 . That definition however should be contaned in `${IPOPT_DEFINITIONS}`. Have you tried moving the add_definitions call in https://github.com/robotology/superquadric-lib/blob/6ed6e48e4e20f9bc0f2e0dc12a6670902f2f7d66/src/SuperquadricLib/SuperquadricModel/CMakeLists.txt#L94 to be **before** the `add_library` call, or even better to convert the `add_definitions` call to [`target_compile_definitions`](https://cmake.org/cmake/help/latest/command/target_compile_definitions.html)?

**Comment by giuliavezzani** [comment]
thanks @traversaro! Following your suggestion I replace:
https://github.com/robotology/superquadric-lib/blob/6ed6e48e4e20f9bc0f2e0dc12a6670902f2f7d66/src/SuperquadricLib/SuperquadricModel/CMakeLists.txt#L94
with
```target_compile_definitions(${LIBRARY_TARGET_NAME} PUBLIC ${IPOPT_DEFINITIONS})```

and I'm able to remove the lines:


```
#define HAVE_CSTDDEF
#include <IpTNLP.hpp>
#undef HAVE_CSTDDEF
```

in the user code.
Thanks!

**Comment by traversaro** [comment]
As you are using `M_PI`, I also suggest to keep the `_USE_MATH_DEFINES` definition, to ensure that your codes compile on MSVC.
