### ISSUE TITLE
Cannot compile with VTK > 8.1

### ISSUE THREAD

**Issue by xEnVrE** [robotology/superquadric-lib#25]
It seems that the `CMakeLists` of the library, and the exported configuration files, look for a specific version of VTK, namely the `8.1`, while in the `README.md` it is indicated that the accepted version is `>= 8.1`.

**Comment by giuliavezzani** [comment]
Fixed in [5e4c46f](5e4c46f44a790b59cc87c0e80a082a26c698abc9). Thanks @xEnVrE for spotting out!
