### ISSUE TITLE
VTK warning during SuperqVis::Visualizer destruction

### ISSUE THREAD

**Issue by xEnVrE** [robotology/superquadric-lib#28]
#### Description of the issue

The following code

```
#include <SuperquadricLibVis/visRenderer.h>

using namespace SuperqVis;

int main(int argc, char** argv])
{   
    Visualizer vis;

    return 0;
}
```

prints out the following **warning**:
```
Generic Warning: In /home/npiga/robot-code/VTK/Common/Core/vtkObjectBase.cxx, line 93
Trying to delete object with non-zero reference count.
```

#### Additional information
**OS:** Ubuntu 16.04
**VTK version:** 8.1.0

**Comment by giuliavezzani** [comment]
I'm aware of this warning. A fix for this is in my todo list. I'd close this issue since this is already mentioned in [#20](https://github.com/robotology/superquadric-lib/issues/20).
