### ISSUE TITLE
Make SuperqModel::Superquadric getters const

### ISSUE THREAD

**Issue by xEnVrE** [robotology/superquadric-lib#29]
I'm opening this issue to ask for a code enhancement.

In this moment all the getter methods of class `SuperqModel::Superquadric`, i.e.
```
getSuperqParams();
getSuperqDims();
getSuperqExps();
getSuperqCenter();
getSuperqAxisAngle();
getSuperqEulerZYZ();         
getSuperqAxes(); 
```
plus the method `insideOutsideF()` are not `const`. 

As a consequence it is not possible to call these methods within a function that uses a `Superquadric` with the assumption that the object will not be modified, e.g.

```
void foo (const Supequadric& superq)
{
    superq.getSuperqParams();
}
```
 without incurring in the following error from the compiler

```
error: passing ‘const SuperqModel::Superquadric’ as ‘this’ argument discards qualifiers [-fpermissive]
```

**Comment by giuliavezzani** [comment]
I'll fix this asap! Thanks for spotting out!

**Comment by giuliavezzani** [comment]
@xEnVrE I made the `get` methods of the class `SuperqModel::Superquadric` `const`. However, I cannot do the same with the `insideOutsideF()`, since that function calls `setSuperqCenter()` and `setSuperqOrientation()` that actually needs to modify some member data.

Let me know if this helps.

**Comment by xEnVrE** [comment]
@giuliavezzani, you are right it is not possible for that method. 

Do you think it is possible to have a slightly different behavior for the method `insideOutsideF()`?  In my mind, when I call that method I am expecting to obtain the evaluation of the function using the current shape of the superquadric and a pose that might be different from the current one. Instead, the current implementation also changes the current pose which might be unexpected given the name of the method. 

Of course, I am not saying that one should change the method in this way in order to have it `const`. What do you think?

**Comment by giuliavezzani** [comment]
@xEnVrE I made the changes to make `insideOutsideF()` a `const `method. It is not a problem actually :smiley: Let me know if it solves your problems.

**Comment by xEnVrE** [comment]
Thank you @giuliavezzani. Now everything compiles successfully.

I will close this.
